default_language_version:
    python: python3
repos:
-   repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0  # Use the ref you want to point at
    hooks:
    -   id: flake8
    -   id: debug-statements
    # -   id: ...
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.660'
    hooks:
    - id: mypy
